# Site
title:              Agencia de Viajes Villegas
bio:                'Agencia de viajes Villegas Donde encontrar tu destino es FACIL'
description:        "agencia de viajes villegas supervisara todo hacerca de tus viajes"
locale:             CDMX
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Comments
disqus_shortname:   default

# Social
analytics-id:       "default"
twitter:            R_Craxker
facebook:           Gael Villegas
instagram:          Crax_ville
github:             CRAXKER4727

# personal
location:           <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d1881.3767081395301!2d-99.0669276!3d19.4230573!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x85d1fc6f81302925%3A0x7dc084d40095b908!2sCentro%20de%20Estudios%20Tecnol%C3%B3gicos%20Industrial%20y%20de%20Servicios%20(CETis%2032)!5e0!3m2!1ses!2smx!4v1648764989380!5m2!1ses!2smx" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>

phone:              5561989826

email:              osiroman12@gmail.com # change this to your email to receive free emails for your contact submissions via Slapform.com

# Other
background_image:   /images/bg.jpg
# Tip: The color palette and other styles can be configured in /_sass/lib/_vars.scss
slapform_thankyou_page: /thank-you

defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
    author:

# Jekyll
permalink:          /blog/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Gems
gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

paginate: 6
paginate_path: "/blog/page:num/"

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]
